# Entregable semana 7
## Sobre la base del entregable de la semana 5
#### - Se agrego un DF que incorpora datos del top 50 actuales del ranking FIFA con el objetivo de saber como les fue durante la fase de grupos del mundial.
#### - Se tomo en cuenta que al momento de levantar los datos de la web, se usaba la posición de los DF siendo esto suceptible a fallos (segun lo indicado).Para resolverlo se usaron las sentencias "try","except" convinado con " if(df.columns==**)"
#### - Se agregaron DISTKEY y SORTKEY a la tabla

### OBJETIVOS ESPECIFICOS DEL ENTREGABLE 2
#### Implementar funcionalidades de la librería Pandas en el código cargándolos en la tabla creada en la misma.
#### Solucionar una situación real de ETL donde puedan llegar a aparecer duplicados durante la ingesta de los datos

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
!pip install lxml

Requirement already satisfied: lxml in /opt/conda/lib/python3.10/site-packages (4.9.2)

In [3]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/conda/lib/python3.10/site-packages (1.0.0)

In [4]:
# para conectarse con cluster de AWS
!pip install redshift_connector

Requirement already satisfied: redshift_connector in /opt/conda/lib/python3.10/site-packages (2.0.911)
Requirement already satisfied: scramp<1.5.0,>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (2023.3)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.7.0 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (4.12.2)
Requirement already satisfied: boto3<2.0.0,>=1.9.201 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (1.26.151)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (2.28.2)
Requirement already satisfied: lxml>=4.6.5 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (4.9.2)
Requirement already satisfied: botocore<2.0.0,>=1.12.201 in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (1.29.151)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (23.1)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from redshift_connector) (67.7.1)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.10/site-packages (from beautifulsoup4<5.0.0,>=4.7.0->redshift_connector) (2.3.2.post1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3<2.0.0,>=1.9.201->redshift_connector) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from boto3<2.0.0,>=1.9.201->redshift_connector) (0.6.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.10/site-packages (from botocore<2.0.0,>=1.12.201->redshift_connector) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.10/site-packages (from botocore<2.0.0,>=1.12.201->redshift_connector) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0,>=2.23.0->redshift_connector) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0,>=2.23.0->redshift_connector) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0,>=2.23.0->redshift_connector) (2022.12.7)
Requirement already satisfied: asn1crypto>=1.5.1 in /opt/conda/lib/python3.10/site-packages (from scramp<1.5.0,>=1.2.0->redshift_connector) (1.5.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.12.201->redshift_connector) (1.16.0)

In [5]:
import pandas as pd
import pickle

In [6]:
# (Creando la conexion)
import os
import dotenv

In [7]:
# cargamos las variables de entorno
dotenv.load_dotenv()

True

In [8]:
# leemos las varaibles de entorno
usuario = os.getenv('User')
passwd = os.getenv('Password')
host = os.getenv('host')
database = os.getenv('db')
my_schema = os.getenv('my_schema')
print(my_schema)

federicobergada_coderhouse

In [9]:
import redshift_connector

conn = redshift_connector.connect(
     host=host,
     database=database,
     port=5439,
     user=usuario,
     password=passwd
  )

In [10]:
conn.rollback() #regresa al inicio del programa, antes de la ejecución de estos cambios. De esta manera, no se deja ninguna operación a medias.
conn.autocommit = True
cursor = conn.cursor()
## Aca hay que cambiar la tabla, primero borro contenido del entregable 1
## cursor.execute(f'DROP TABLE if exists {my_schema}.faseDeGruposMundial')
## La vuelvo a crear con las nuevas columnas 
cursor.execute(f'CREATE TABLE if not exists {my_schema}.faseDeGruposMundial(Selección VARCHAR(30), Pts INT, PJ INT, PG INT, PE INT, PP INT, GF INT, GC INT, Dif VARCHAR(5),Posición_Fifa float, Continente VARCHAR(30), Confederación VARCHAR(30), Total_puntos_fifa float) DISTKEY(Selección) SORTKEY(Selección, Posición_Fifa, Total_puntos_fifa)')

In [11]:
# Lee los datos de la página para obtener los resultados de la fase de grupos, filtranndo por aquellos df con columna dif
dfs = pd.read_html('https://es.wikipedia.org/wiki/Copa_Mundial_de_F%C3%BAtbol_de_2022',match='Dif')

In [12]:
# con el try y el except filtra solo los df que tienen las columnas mencionadas (son los df de los grupos) 
# y nos independizamos de llamar a los dataframes por su ubicación 

dffg=pd.DataFrame()

import numpy as np

for df in dfs: 
    try:
        if (df.columns == ['Selección', 'Pts', 'PJ', 'PG', 'PE', 'PP', 'GF', 'GC', 'Dif']).all():
            for i in range(len(df.index)):
                list_item = []
                for j in range(9):
                    if type(list(df.iloc[i])[j])  is np.int64:
                        list_item.append(list(df.iloc[i])[j].item())
                    elif type(list(df.iloc[i])[j])  is np.float64:
                        list_item.append(list(df.iloc[i])[j].item())
                    else:
                        list_item.append(list(df.iloc[i])[j])
                dffg = pd.concat([dffg, pd.DataFrame([list_item])], ignore_index=True)
                     
    except ValueError:
        pass
dffg.rename(columns = {dffg.columns[0]:'Selección',
                                    dffg.columns[1]:'Pts',
                                    dffg.columns[2]:'PJ',
                                    dffg.columns[3]:'PG',
                                    dffg.columns[4]:'PE',
                                    dffg.columns[5]:'PP',
                                    dffg.columns[6]:'GF',
                                    dffg.columns[7]:'GC',
                                    dffg.columns[8]:'Dif'},inplace = True)
dffg

         Selección  Pts  PJ  PG  PE  PP  GF  GC Dif
0     Países Bajos    7   3   2   1   0   5   1   4
1          Senegal    6   3   2   0   1   5   4   1
2          Ecuador    4   3   1   1   1   4   3   1
3            Catar    0   3   0   0   3   1   7  –6
4       Inglaterra    7   3   2   1   0   9   2   7
5   Estados Unidos    5   3   1   2   0   2   1   1
6             Irán    3   3   1   0   2   4   7  –3
7            Gales    1   3   0   1   2   1   6  –5
8        Argentina    6   3   2   0   1   5   2   3
9          Polonia    4   3   1   1   1   2   2   0
10          México    4   3   1   1   1   2   3  –1
11  Arabia Saudita    3   3   1   0   2   3   5  –2
12         Francia    6   3   2   0   1   6   3   3
13       Australia    6   3   2   0   1   3   4  –1
14           Túnez    4   3   1   1   1   1   1   0
15       Dinamarca    1   3   0   1   2   1   3  –2
16           Japón    6   3   2   0   1   4   3   1
17          España    4   3   1   1   1   9   3   6
18        Alemania    4   3   1   1   1   6   5   1
19      Costa Rica    3   3   1   0   2   3  11  –8
20       Marruecos    7   3   2   1   0   4   1   3
21         Croacia    5   3   1   2   0   4   1   3
22         Bélgica    4   3   1   1   1   1   2  –1
23          Canadá    0   3   0   0   3   2   7  –5
24          Brasil    6   3   2   0   1   3   1   2
25           Suiza    6   3   2   0   1   4   3   1
26         Camerún    4   3   1   1   1   4   4   0
27          Serbia    1   3   0   1   2   5   8  –3
28        Portugal    6   3   2   0   1   6   4   2
29   Corea del Sur    4   3   1   1   1   4   4   0
30         Uruguay    4   3   1   1   1   2   2   0
31           Ghana    3   3   1   0   2   5   7  –2

In [13]:
# Me traigo el top 50 del ranking Fifa
url='https://es.wikipedia.org/wiki/Anexo:Estad%C3%ADsticas_de_la_clasificaci%C3%B3n_mundial_de_la_FIFA'
fifadfs=pd.read_html(url,na_values='$Null$')

for fifadf in fifadfs: 
    try:
        if (fifadf.columns == ['Pos.', 'V', 'Selección', 'Continente', 'Confederación','Total puntos']).all():
            print(fifadf)
            break
    except ValueError:
        pass

    Pos.    V        Selección         Continente Confederación  Total puntos
0      1  1.0        Argentina    América del Sur      Conmebol       1840.93
1      2  1.0          Francia             Europa          UEFA       1838.45
2      3  2.0           Brasil    América del Sur      Conmebol       1834.21
3      4  NaN          Bélgica             Europa          UEFA       1792.53
4      5  NaN       Inglaterra             Europa          UEFA       1792.43
5      6  NaN     Países Bajos             Europa          UEFA       1731.23
6      7  NaN          Croacia             Europa          UEFA       1730.02
7      8  NaN           Italia             Europa          UEFA       1713.66
8      9  NaN         Portugal             Europa          UEFA       1707.22
9     10  NaN           España             Europa          UEFA       1682.85
10    11  NaN        Marruecos             África           CAF       1677.79
11    12  NaN            Suiza             Europa          UEFA       1664.24
12    13  NaN   Estados Unidos  América del Norte      Concacaf       1653.77
13    14  NaN         Alemania             Europa          UEFA       1647.42
14    15  NaN           México  América del Norte      Concacaf       1631.87
15    16  NaN          Uruguay    América del Sur      Conmebol       1631.29
16    17  NaN         Colombia    América del Sur      Conmebol       1617.08
17    18  1.0          Senegal             África           CAF       1613.21
18    19  1.0        Dinamarca             Europa          UEFA       1594.53
19    20  NaN            Japón               Asia           AFC       1588.59
20    21  NaN             Perú    América del Sur      Conmebol       1561.20
21    22  1.0           Suecia             Europa          UEFA       1558.70
22    23  1.0          Polonia             Europa          UEFA       1553.76
23    24  NaN             Irán               Asia           AFC       1553.23
24    25  4.0           Serbia             Europa          UEFA       1541.52
25    26  2.0            Gales             Europa          UEFA       1538.95
26    27  2.0    Corea del Sur               Asia           AFC       1536.01
27    28  2.0            Túnez             África           CAF       1535.76
28    29  2.0        Australia            Oceanía           AFC       1532.79
29    30  4.0          Ucrania             Europa          UEFA       1530.04
30    31  NaN            Chile    América del Sur      Conmebol       1511.32
31    32  2.0          Austria             Europa          UEFA       1508.24
32    33  3.0          Hungría             Europa          UEFA       1504.24
33    34  6.0          Argelia             África           CAF       1504.19
34    35  4.0           Egipto             África           CAF       1500.67
35    36  6.0          Escocia             Europa          UEFA       1500.52
36    37  NaN            Rusia      Europa y Asia          UEFA       1495.53
37    38  NaN  República Checa             Europa          UEFA       1495.04
38    39  7.0       Costa Rica    América Central      Concacaf       1491.12
39    40  5.0          Nigeria             África           CAF       1480.80
40    41  NaN          Ecuador    América del Sur      Conmebol       1478.13
41    42  9.0          Camerún             África           CAF       1470.21
42    43  1.0          Turquía             Europa          UEFA       1465.70
43    44  1.0          Noruega             Europa          UEFA       1463.77
44    45  2.0  Costa de Marfil             África           CAF       1449.95
45    46  6.0          Rumania             Europa          UEFA       1444.58
46    47  6.0           Canadá  América del Norte      Concacaf       1442.66
47    48  2.0         Paraguay    América del Sur      Conmebol       1440.65
48    49  1.0          Irlanda             Europa          UEFA       1436.31
49    50  NaN     Burkina Faso             África           CAF       1433.91

In [14]:
# la idea es ver como les fue a los top 50 (actuales en el último mundial)
# merge entre las dos tablas, y se eliminan los que son nulos, es decir quienes no estaban en el top 50 y lo ordeno por posición
dffg_fifa_t = pd.merge(dffg, fifadf, on='Selección',how='left')
dffg_fifa = dffg_fifa_t[['Selección', 'Pts', 'PJ', 'PG', 'PE', 'PP', 'GF', 'GC', 'Dif','Pos.', 'Continente', 'Confederación','Total puntos']].dropna().sort_values(by=['Pos.'],ignore_index= True)
dffg_fifa

,Selección,Pts,PJ,PG,PE,PP,GF,GC,Dif,Pos.,Continente,Confederación,Total puntos
0,Argentina,6,3,2,0,1,5,2,3,1.0,América del Sur,Conmebol,1840.93
1,Francia,6,3,2,0,1,6,3,3,2.0,Europa,UEFA,1838.45
2,Brasil,6,3,2,0,1,3,1,2,3.0,América del Sur,Conmebol,1834.21
3,Bélgica,4,3,1,1,1,1,2,–1,4.0,Europa,UEFA,1792.53
4,Inglaterra,7,3,2,1,0,9,2,7,5.0,Europa,UEFA,1792.43
5,Países Bajos,7,3,2,1,0,5,1,4,6.0,Europa,UEFA,1731.23
6,Croacia,5,3,1,2,0,4,1,3,7.0,Europa,UEFA,1730.02
7,Portugal,6,3,2,0,1,6,4,2,9.0,Europa,UEFA,1707.22
8,España,4,3,1,1,1,9,3,6,10.0,Europa,UEFA,1682.85
9,Marruecos,7,3,2,1,0,4,1,3,11.0,África,CAF,1677.79
10,Suiza,6,3,2,0,1,4,3,1,12.0,Europa,UEFA,1664.24
11,Estados Unidos,5,3,1,2,0,2,1,1,13.0,América del Norte,Concacaf,1653.77
12,Alemania,4,3,1,1,1,6,5,1,14.0,Europa,UEFA,1647.42
13,México,4,3,1,1,1,2,3,–1,15.0,América del Norte,Concacaf,1631.87
14,Uruguay,4,3,1,1,1,2,2,0,16.0,América del Sur,Conmebol,1631.29
15,Senegal,6,3,2,0,1,5,4,1,18.0,África,CAF,1613.21
16,Dinamarca,1,3,0,1,2,1,3,–2,19.0,Europa,UEFA,1594.53
17,Japón,6,3,2,0,1,4,3,1,20.0,Asia,AFC,1588.59
18,Polonia,4,3,1,1,1,2,2,0,23.0,Europa,UEFA,1553.76
19,Irán,3,3,1,0,2,4,7,–3,24.0,Asia,AFC,1553.23
20,Serbia,1,3,0,1,2,5,8,–3,25.0,Europa,UEFA,1541.52
21,Gales,1,3,0,1,2,1,6,–5,26.0,Europa,UEFA,1538.95
22,Corea del Sur,4,3,1,1,1,4,4,0,27.0,Asia,AFC,1536.01
23,Túnez,4,3,1,1,1,1,1,0,28.0,África,CAF,1535.76
24,Australia,6,3,2,0,1,3,4,–1,29.0,Oceanía,AFC,1532.79
25,Costa Rica,3,3,1,0,2,3,11,–8,39.0,América Central,Concacaf,1491.12
26,Ecuador,4,3,1,1,1,4,3,1,41.0,América del Sur,Conmebol,1478.13
27,Camerún,4,3,1,1,1,4,4,0,42.0,África,CAF,1470.21
28,Canadá,0,3,0,0,3,2,7,–5,47.0,América del Norte,Concacaf,1442.66

In [15]:
#chequedo duplicados
cheqdup=pd.DataFrame()
cheqdup=dffg_fifa.drop_duplicates()
if len(cheqdup) == len(dffg_fifa):
    print("Sin duplicados")
else:
    print("Es necesario remover duplicados")

Sin duplicados

In [16]:
# Insertar DataFrame en redshift
sql = "INSERT INTO federicobergada_coderhouse.faseDeGruposMundial(Selección, Pts, PJ, PG, PE, PP, GF, GC, Dif, Posición_Fifa, Continente, Confederación, Total_puntos_fifa) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" 
for i in range(len(dffg_fifa.index)):
    list_item = []
    for j in range(13):
        if type(list(dffg_fifa.iloc[i])[j])  is np.int64:
            list_item.append(list(dffg_fifa.iloc[i])[j].item())
        elif type(list(dffg_fifa.iloc[i])[j])  is np.float64:
            list_item.append(list(dffg_fifa.iloc[i])[j].item())
        else:
            list_item.append(list(dffg_fifa.iloc[i])[j])
        #print(type(list_item[len(list_item)-1]))
    cursor.execute(sql, list_item)
    

conn.commit() 
cursor.close()